
/******************************************************************************
*
*   FILE
*   ----
*   DSService.c
*
*   History
*   -------
*   2018-05-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_DSService_startService(OV_STRING JsonInput, OV_STRING *JsonOutput) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_DSService_stopService(void) {

    return OV_ERR_OK;
}

