
/******************************************************************************
*
*   FILE
*   ----
*   Part.c
*
*   History
*   -------
*   2018-05-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_AddDBWrapper_set(
    OV_INSTPTR_openAASDiscoveryServer_Part          pobj,
    const OV_BOOL  value
) {
    pobj->v_AddDBWrapper = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_RemoveDBWrapper_set(
    OV_INSTPTR_openAASDiscoveryServer_Part          pobj,
    const OV_BOOL  value
) {
    pobj->v_RemoveDBWrapper = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_AddDSService_set(
    OV_INSTPTR_openAASDiscoveryServer_Part          pobj,
    const OV_BOOL  value
) {
    pobj->v_AddDSService = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_RemoveDSService_set(
    OV_INSTPTR_openAASDiscoveryServer_Part          pobj,
    const OV_BOOL  value
) {
    pobj->v_RemoveDSService = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_UseDSServices_set(
    OV_INSTPTR_openAASDiscoveryServer_Part          pobj,
    const OV_BOOL  value
) {
    pobj->v_UseDSServices = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_ConfigDSServices_set(
    OV_INSTPTR_openAASDiscoveryServer_Part          pobj,
    const OV_BOOL  value
) {
    pobj->v_ConfigDSServices = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ACCESS openAASDiscoveryServer_Part_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_Part pinst = Ov_StaticPtrCast(openAASDiscoveryServer_Part, pobj);

    return (OV_ACCESS)0;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_Part pinst = Ov_StaticPtrCast(openAASDiscoveryServer_Part, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_addDBWrapper(OV_STRING *DBWrapper) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_removeDBWrapper(OV_STRING *DBWrapper) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Part_useDSServices(OV_STRING *DSService) {

    return OV_ERR_OK;
}

