
/******************************************************************************
*
*   FILE
*   ----
*   Registration.c
*
*   History
*   -------
*   2018-05-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_AddSEWrapper_set(
    OV_INSTPTR_openAASDiscoveryServer_Registration          pobj,
    const OV_BOOL  value
) {
    pobj->v_AddSEWrapper = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_RemoveSEWrapper_set(
    OV_INSTPTR_openAASDiscoveryServer_Registration          pobj,
    const OV_BOOL  value
) {
    pobj->v_RemoveSEWrapper = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_ProcessRegistrationMessage_set(
    OV_INSTPTR_openAASDiscoveryServer_Registration          pobj,
    const OV_BOOL  value
) {
    pobj->v_ProcessRegistrationMessage = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_ProcessUnregistrationMessage_set(
    OV_INSTPTR_openAASDiscoveryServer_Registration          pobj,
    const OV_BOOL  value
) {
    pobj->v_ProcessUnregistrationMessage = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ACCESS openAASDiscoveryServer_Registration_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_Registration pinst = Ov_StaticPtrCast(openAASDiscoveryServer_Registration, pobj);

    return (OV_ACCESS)0;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_Registration pinst = Ov_StaticPtrCast(openAASDiscoveryServer_Registration, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = openAASDiscoveryServer_Part_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_removeSEWrapper(OV_STRING *SEWrapper) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_addDSService(OV_STRING *DSService) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_removeDSService(OV_STRING *DSService) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_configureDSService(OV_STRING *DBWrapper, OV_STRING *URMSWrapper, OV_STRING *CAWrapper, OV_STRING *SEWrapper, OV_STRING DSService) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_getRegistrationMessage(const OV_STRING JsonInput, OV_STRING *JsonOutput, OV_STRING *errorMessage) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Registration_getUnregistrationMessage(const OV_STRING JsonInput, OV_STRING *JsonOutput, OV_STRING *errorMessage) {

    return OV_ERR_OK;
}

