
/******************************************************************************
*
*   FILE
*   ----
*   Search.c
*
*   History
*   -------
*   2018-05-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"
#include "libov/ov_path.h"


OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_AddSEWrapper_set(
    OV_INSTPTR_openAASDiscoveryServer_Search          pobj,
    const OV_BOOL  value
) {
    pobj->v_AddSEWrapper = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_RemoveSEWrapper_set(
    OV_INSTPTR_openAASDiscoveryServer_Search          pobj,
    const OV_BOOL  value
) {
    pobj->v_RemoveSEWrapper = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_ProcessSearchMessage_set(
    OV_INSTPTR_openAASDiscoveryServer_Search          pobj,
    const OV_BOOL  value
) {
    pobj->v_ProcessSearchMessage = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ACCESS openAASDiscoveryServer_Search_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
	switch(pelem->elemtype) {
		case OV_ET_VARIABLE:
			if(pelem->elemunion.pvar->v_offset >= offsetof(OV_INST_ov_object,__classinfo)) {
				if(pelem->elemunion.pvar->v_vartype == OV_VT_CTYPE)
					return OV_AC_NONE;
				else{
					if((pelem->elemunion.pvar->v_varprops & OV_VP_DERIVED)){
						if((pelem->elemunion.pvar->v_varprops & OV_VP_SETACCESSOR)){
							return OV_AC_READWRITE;
						} else {
							return OV_AC_READ;
						}
					} else {
						return OV_AC_READWRITE;
					}
				}
			}
		break;
		default:
		break;
	}

	return ov_object_getaccess(pobj, pelem, pticket);
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_Search pinst = Ov_StaticPtrCast(openAASDiscoveryServer_Search, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = openAASDiscoveryServer_Part_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_addSEWrapper(OV_INSTPTR_openAASDiscoveryServer_Part pinst, OV_STRING *SEWrapper, OV_UINT veclen) {
	OV_INSTPTR_ov_object pobj = NULL;
	OV_INSTPTR_openAASDiscoveryServer_Search pSearch = NULL;
	pSearch = Ov_DynamicPtrCast(openAASDiscoveryServer_Search, pinst);
	if (!pSearch){
		return OV_ERR_BADOBJTYPE;
	}
	for (OV_UINT i = 0; i < veclen; i++){
		pobj = ov_path_getobjectpointer(SEWrapper[i], 2);
		if (Ov_CanCastTo(openAASDiscoveryServer_SEWrapper, pobj) == FALSE){
			return OV_ERR_BADOBJTYPE;
		}
		if (pSearch->v_SEWrapper.veclen == 0){
			Ov_SetDynamicVectorLength(&pSearch->v_SEWrapper, pSearch->v_SEWrapper.veclen + 1, STRING);
			ov_string_setvalue(&pSearch->v_SEWrapper.value[pSearch->v_SEWrapper.veclen - 1], SEWrapper[i]);
			continue;
		}
		for (OV_UINT j = 0; j < pSearch->v_SEWrapper.veclen; j++){
			if (ov_string_compare(SEWrapper[i], pSearch->v_SEWrapper.value[j]) == OV_STRCMP_EQUAL){
				break;
			}
			if (j == pSearch->v_SEWrapper.veclen - 1){
				Ov_SetDynamicVectorLength(&pSearch->v_SEWrapper, pSearch->v_SEWrapper.veclen + 1, STRING);
				ov_string_setvalue(&pSearch->v_SEWrapper.value[pSearch->v_SEWrapper.veclen - 1], SEWrapper[i]);
			}
		}
	}
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_removeSEWrapper(OV_INSTPTR_openAASDiscoveryServer_Part pinst, OV_STRING *SEWrapper, OV_UINT veclen) {
	OV_INSTPTR_openAASDiscoveryServer_Search pSearch = NULL;
	pSearch = Ov_DynamicPtrCast(openAASDiscoveryServer_Search, pinst);
	if (!pSearch){
		return OV_ERR_BADOBJTYPE;
	}
	for (OV_UINT i = 0; i < veclen; i++){
		for (OV_UINT j = 0; j < pSearch->v_SEWrapper.veclen; j++){
			if (ov_string_compare(SEWrapper[i], pSearch->v_SEWrapper.value[j]) == OV_STRCMP_EQUAL){
				for(OV_UINT k = j; k < pSearch->v_SEWrapper.veclen-1; k++){
					ov_string_setvalue(&pSearch->v_SEWrapper.value[k], pSearch->v_SEWrapper.value[k+1]);
				}
				Ov_SetDynamicVectorLength(&pSearch->v_SEWrapper, pSearch->v_SEWrapper.veclen - 1, STRING);
			}
		}
	}
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_addDSService(OV_INSTPTR_openAASDiscoveryServer_Part pinst, OV_STRING *DSService, OV_UINT veclen) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_removeDSService(OV_INSTPTR_openAASDiscoveryServer_Part pinst, OV_STRING *DSService, OV_UINT veclen) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_configureDSService(OV_INSTPTR_openAASDiscoveryServer_Part pinst, OV_STRING *DBWrapper, OV_UINT veclenDBWrapper, OV_STRING *URMSWrapper, OV_UINT veclenURMSWrapper, OV_STRING *CAWrapper, OV_UINT veclenCAWrapper, OV_STRING *SEWrapper, OV_UINT veclenSEWrapper, OV_STRING DSService) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_Search_getSearchMessage(OV_INSTPTR_openAASDiscoveryServer_Part pinst, const OV_STRING JsonInput, OV_STRING *JsonOutput, OV_STRING *errorMessage) {

    return OV_ERR_OK;
}

