
/******************************************************************************
*
*   FILE
*   ----
*   SEWrapper.c
*
*   History
*   -------
*   2018-05-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openAASDiscoveryServer
#define OV_COMPILE_LIBRARY_openAASDiscoveryServer
#endif


#include "openAASDiscoveryServer.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_StartConnect_set(
    OV_INSTPTR_openAASDiscoveryServer_SEWrapper          pobj,
    const OV_BOOL  value
) {
    pobj->v_StartConnect = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ACCESS openAASDiscoveryServer_SEWrapper_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_SEWrapper pinst = Ov_StaticPtrCast(openAASDiscoveryServer_SEWrapper, pobj);

    return (OV_ACCESS)0;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    //OV_INSTPTR_openAASDiscoveryServer_SEWrapper pinst = Ov_StaticPtrCast(openAASDiscoveryServer_SEWrapper, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_connect(void) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_disconnect(void) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_storeData(void) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT openAASDiscoveryServer_SEWrapper_searchData(void){

    return OV_ERR_OK;
}

