
/******************************************************************************
*
*   FILE
*   ----
*   DSRegistrationServiceType1.c
*
*   History
*   -------
*   2018-05-14   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_DSServices
#define OV_COMPILE_LIBRARY_DSServices
#endif


#include "DSServices.h"
#include "json_helper.h"
#include "service_helper.h"

struct endpoint{
	OV_STRING protocolType;
	OV_STRING endpointString;
};

OV_DLLFNCEXPORT OV_RESULT DSServices_DSRegistrationServiceType1_executeService(OV_INSTPTR_openAASDiscoveryServer_DSService pinst, const json_data JsonInput, OV_STRING *JsonOutput, OV_STRING *errorMessage) {
    /*    
    *   local variables
    */
	// Parsing Body
	OV_UINT arraySize = 0;
	struct endpoint *endpoints = NULL;
	OV_STRING assetID = NULL;
	OV_STRING_VEC tags;
	tags.value = NULL;
	tags.veclen = 0;
	Ov_SetDynamicVectorLength(&tags, 4, STRING);
	ov_string_setvalue(&tags.value[0], "componentID");
	ov_string_setvalue(&tags.value[1], "securityKey");
	ov_string_setvalue(&tags.value[2], "endpoints");
	ov_string_setvalue(&tags.value[3], "assetID");
	OV_UINT_VEC tokenIndex;
	tokenIndex.value = NULL;
	tokenIndex.veclen = 0;
	Ov_SetDynamicVectorLength(&tokenIndex, 4, UINT);

	jsonGetTokenIndexByTags(tags, JsonInput, 1, &tokenIndex);

	OV_STRING componentID = NULL;
	jsonGetValueByToken(JsonInput.js, &JsonInput.token[tokenIndex.value[0]+1], &componentID);
	OV_STRING securityKey = NULL;
	jsonGetValueByToken(JsonInput.js, &JsonInput.token[tokenIndex.value[1]+1], &securityKey);

	// check securityKey
	OV_RESULT resultOV = checkSecurityKey(pinst->v_DBWrapperUsed, componentID, securityKey);
	if (resultOV){
		ov_string_setvalue(errorMessage, "SecurityKey is not correct");
		goto FINALIZE;
	}

	// get registrationData
	// get endpoints from JSON
	arraySize = JsonInput.token[tokenIndex.value[2]+1].size;
	endpoints = malloc(sizeof(struct endpoint)*arraySize);
	for (OV_UINT i = 0; i < arraySize; i++){
		endpoints[i].protocolType = NULL;
		// value + 2 start of objects + i*5 next object + 2/4 values of protocolType and endpoint
		jsonGetValueByToken(JsonInput.js, &JsonInput.token[tokenIndex.value[2]+2+i*5+2], &endpoints[i].protocolType);
		endpoints[i].endpointString = NULL;
		jsonGetValueByToken(JsonInput.js, &JsonInput.token[tokenIndex.value[2]+2+i*5+4], &endpoints[i].endpointString);
	}
	// get assetID from JSON
	jsonGetValueByToken(JsonInput.js, &JsonInput.token[tokenIndex.value[3]+1], &assetID);

	// Insert endpoints in database

	// TODO: Extend to multiDBWrapper
	OV_INSTPTR_openAASDiscoveryServer_DBWrapper pDBWrapper = NULL;
	OV_VTBLPTR_openAASDiscoveryServer_DBWrapper pDBWrapperVTable = NULL;
	pDBWrapper = Ov_DynamicPtrCast(openAASDiscoveryServer_DBWrapper, ov_path_getobjectpointer(pinst->v_DBWrapperUsed.value[0], 2));
	if (!pDBWrapper){
		ov_string_setvalue(errorMessage, "Internel Error");
		ov_logfile_error("Could not find DBWrapper Object");
		goto FINALIZE;
	}
	Ov_GetVTablePtr(openAASDiscoveryServer_DBWrapper,pDBWrapperVTable, pDBWrapper);
	OV_STRING table  = "demoDB";
	OV_STRING tmpFields[6];
	OV_STRING tmpValues[6];
	tmpFields[0] = "ComponentID";
	tmpFields[1] = "Certificate";
	tmpFields[2] = "SecurityKey";
	tmpFields[3] = "ProtocolType";
	tmpFields[4] = "EndpointString";
	tmpFields[5] = "AssetID";

	tmpValues[0] = NULL;
	ov_string_print(&tmpValues[0], "'%s'", componentID);
	tmpValues[1] = "''";
	tmpValues[2] = "''";
	tmpValues[5] = "''";

	for (OV_UINT i = 0; i < arraySize; i++){
		tmpValues[3] = NULL;
		ov_string_print(&tmpValues[3], "'%s'", endpoints[i].protocolType);
		tmpValues[4] = NULL;
		ov_string_print(&tmpValues[4], "'%s'", endpoints[i].endpointString);
		resultOV = pDBWrapperVTable->m_insertData(table, tmpFields, 6, tmpValues, 6);
		ov_string_setvalue(&tmpValues[3], NULL);
		ov_string_setvalue(&tmpValues[4], NULL);
	}

	// Insert assetID in database
	if (assetID){
		tmpValues[0] = NULL;
		ov_string_print(&tmpValues[0], "'%s'", componentID);
		tmpValues[1] = "''";
		tmpValues[2] = "''";
		tmpValues[3] = "''";
		tmpValues[4] = "''";
		tmpValues[5] = NULL;
		ov_string_print(&tmpValues[5], "'%s'", assetID);
		resultOV = pDBWrapperVTable->m_insertData(table, tmpFields, 6, tmpValues, 6);
		ov_string_setvalue(&tmpValues[5], NULL);
	}

	FINALIZE:
	ov_string_print(JsonOutput, "\"body\":{}");
	Ov_SetDynamicVectorLength(&tags, 0, STRING);
	Ov_SetDynamicVectorLength(&tokenIndex, 0, UINT);
	ov_string_setvalue(&componentID, NULL);
	ov_string_setvalue(&securityKey, NULL);
	ov_string_setvalue(&assetID, NULL);
	for (OV_UINT i = 0; i < arraySize; i++){
		ov_string_setvalue(&endpoints[i].protocolType, NULL);
		ov_string_setvalue(&endpoints[i].endpointString, NULL);
	}
	if (endpoints)
		free(endpoints);
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ACCESS DSServices_DSRegistrationServiceType1_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */

	switch(pelem->elemtype) {
		case OV_ET_VARIABLE:
			if(pelem->elemunion.pvar->v_offset >= offsetof(OV_INST_ov_object,__classinfo)) {
				if(pelem->elemunion.pvar->v_vartype == OV_VT_CTYPE)
					return OV_AC_NONE;
				else{
					if(pelem->elemunion.pvar->v_flags == 256) { // InputFlag is set
						return OV_AC_READWRITE;
					}
					/* Nicht FB? */
					if(pelem->elemunion.pvar->v_varprops & OV_VP_SETACCESSOR) {
						return OV_AC_READWRITE;
					}
					return OV_AC_READ;
				}
			}
		break;
		default:
		break;
	}

	return ov_object_getaccess(pobj, pelem, pticket);
}

