
/******************************************************************************
*
*   FILE
*   ----
*   DSRegistrationServiceType1.c
*
*   History
*   -------
*   2018-05-11   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_DSServices
#define OV_COMPILE_LIBRARY_DSServices
#endif


#include "DSServices.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT DSServices_DSRegistrationServiceType1_executeService(const json_data JsonInput, OV_STRING *JsonOutput) {
    /*    
    *   local variables
    */
	ov_string_setvalue(JsonOutput, "\"body\":{}");
    return OV_ERR_OK;
}

