
/******************************************************************************
*
*   FILE
*   ----
*   DSSecurityServiceType1.c
*
*   History
*   -------
*   2018-05-11   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_DSServices
#define OV_COMPILE_LIBRARY_DSServices
#endif


#include "DSServices.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT DSServices_DSSecurityServiceType1_executeService(const json_data JsonInput, OV_STRING *JsonOutput) {
    /*    
    *   local variables
    */
	OV_STRING certificate = NULL;
	OV_STRING securityKey = NULL;
	ov_string_setvalue(&certificate, "certificate of DS");
	ov_string_setvalue(&securityKey, "securityKey123");
	ov_string_print(JsonOutput, "\"body\":{\"certificate\":\"%s\", \"securityKey\":\"%s\"}", certificate, securityKey);
	ov_string_setvalue(&certificate, NULL);
	ov_string_setvalue(&securityKey, NULL);
    return OV_ERR_OK;
}

