
/******************************************************************************
*
*   FILE
*   ----
*   MySQL.c
*
*   History
*   -------
*   2018-07-02   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_Databases
#define OV_COMPILE_LIBRARY_Databases
#endif


#include "Databases.h"
#include "libov/ov_macros.h"

OV_INSTPTR_Databases_MySQL MYSQL_pinst = NULL;

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_connect(void) {

	// allocate and initialise MYSQL handler
	MYSQL_pinst->v_db = mysql_init(NULL);

	if(MYSQL_pinst->v_db == NULL) {
		return OV_ERR_GENERIC;
	}

	// connect to database. Arguments:
	// 1. mysql db handle
	// 2. host name
	// 3. user name
	// 4. password
	if(mysql_real_connect(MYSQL_pinst->v_db, MYSQL_pinst->v_Endpoint, MYSQL_pinst->v_User, MYSQL_pinst->v_Password, MYSQL_pinst->v_database, 0, NULL, 0) == NULL) {
		mysql_close(MYSQL_pinst->v_db);
		return OV_ERR_GENERIC;
	}

	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_disconnect(void) {
	mysql_close(MYSQL_pinst->v_db);

	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_insertData(const OV_STRING table, const OV_STRING* fields, OV_UINT fieldsLen,
													 const OV_STRING* values, OV_UINT valuesLen) {
	if(fieldsLen != valuesLen) {
		return OV_ERR_BADPARAM;
	}
	// build up INSERT query
	OV_STRING query = NULL;
	ov_string_setvalue(&query, "INSERT INTO ");
	ov_string_print(&query, "%s%s ", query, table);
	ov_string_print(&query, "%s%s", query, "(");
	for(int i = 0; i < fieldsLen; i++) {
		if(i == fieldsLen-1) {
			ov_string_print(&query, "%s%s) ", query, fields[i]);
		} else {
			ov_string_print(&query, "%s%s, ", query, fields[i]);
		}
	}
	ov_string_print(&query, "%s%s", query, "VALUES (");
	for(int i = 0; i < fieldsLen; i++) {
		if(i == fieldsLen-1) {
			ov_string_print(&query, "%s%s); ", query, values[i]);
		} else {
			ov_string_print(&query, "%s%s, ", query, values[i]);
		}
	}

	OV_RESULT res = Databases_MySQL_execQuery(query);
	return res;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_selectData(const OV_STRING table, const OV_STRING* fields, OV_UINT fieldsLen, const OV_STRING* whereFields,
													 OV_UINT whereFieldsLen, OV_STRING* whereValues, OV_UINT whereValuesLen, OV_STRING_VEC* result) {
	if(whereFieldsLen != whereValuesLen) {
		return OV_ERR_BADPARAM;
	}
	// build up SELECT query
	OV_STRING query = NULL;
	ov_string_setvalue(&query, "SELECT DISTINCT");
	for(int i = 0; i < fieldsLen; i++) {
		if(i != fieldsLen-1) {
			ov_string_print(&query, "%s %s,", query, fields[i]);
		} else {
			ov_string_print(&query, "%s %s", query, fields[i]);
		}
	}
	if(!fieldsLen) ov_string_print(&query, "%s %s ", query, "*");
	ov_string_print(&query, "%s %s", query, "FROM");
	ov_string_print(&query, "%s %s", query, table);
	if (fieldsLen){
		ov_string_print(&query, "%s %s", query, "WHERE");
		for(int i = 0; i < fieldsLen; i++) {
			if(i != fieldsLen-1) {
				ov_string_print(&query, "%s %s IS NOT NULL AND", query, fields[i]);
				ov_string_print(&query, "%s %s != \"\" AND", query, fields[i]);
			} else {
				ov_string_print(&query, "%s %s IS NOT NULL AND", query, fields[i]);
				ov_string_print(&query, "%s %s != \"\" AND", query, fields[i]);
			}
		}
	}
	if(whereFieldsLen) {
		if (!fieldsLen)	ov_string_print(&query, "%s %s", query, "WHERE");
		for(int i = 0; i < whereFieldsLen; i++) {
			if(i != whereFieldsLen-1) {
				ov_string_print(&query, "%s %s = %s AND", query, whereFields[i], whereValues[i]);
			} else {
				ov_string_print(&query, "%s %s = %s", query, whereFields[i], whereValues[i]);
			}
		}
	}
	ov_string_print(&query, "%s%s", query, ";");

	OV_RESULT res = Databases_MySQL_execQuery(query);

	if(res != OV_ERR_OK) {
		return res;
	}

	MYSQL_RES* query_result = mysql_store_result(MYSQL_pinst->v_db);

	if(query_result == NULL) {
		mysql_close(MYSQL_pinst->v_db);
		return OV_ERR_GENERIC;
	}

	int num_fields = mysql_num_fields(result);
	MYSQL_ROW row;

	// do smth here with the data

	mysql_free_result(query_result);

	return res;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_deleteData(const OV_STRING table, const OV_STRING* fields, OV_UINT fieldsLen, const OV_STRING* values, OV_UINT valuesLen) {

	// build up DELETE query
	OV_STRING query = NULL;
	ov_string_setvalue(&query, "DELETE FROM ");
	ov_string_print(&query, "%s%s ", query, table);
	if(fieldsLen) {
		ov_string_print(&query, "%s%s ", query, "WHERE");
		for(int i = 0; i < fieldsLen; i++) {
			if(i != fieldsLen-1) {
				ov_string_print(&query, "%s%s = %s, ", query, fields[i], values[i]);
			} else {
				ov_string_print(&query, "%s%s = %s;", query, fields[i], values[i]);
			}
		}
	}

	//ov_logfile_info("%s", query);

	OV_RESULT res = Databases_MySQL_execQuery(query);
	return res;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_updateData(const OV_STRING table, const OV_STRING* fields, OV_UINT fieldsLen, const OV_STRING* fieldValues, OV_UINT fieldValuesLen, const OV_STRING* whereFields, OV_UINT whereFieldsLen, OV_STRING* whereValues, OV_UINT whereValuesLen) {
	// build up UPDATE query
	OV_STRING query = NULL;
	ov_string_setvalue(&query, "UPDATE");
	ov_string_print(&query, "%s %s", query, table);
	if(fieldsLen) {
		ov_string_print(&query, "%s %s", query, "SET");
		for(int i = 0; i < fieldsLen; i++) {
			if(i != fieldsLen-1) {
				ov_string_print(&query, "%s %s = %s,", query, fields[i], fieldValues[i]);
			} else {
				ov_string_print(&query, "%s %s = %s", query, fields[i], fieldValues[i]);
			}
		}
	}
	if(whereFieldsLen) {
		ov_string_print(&query, "%s %s", query, "WHERE");
		for(int i = 0; i < fieldsLen; i++) {
			if(i != fieldsLen-1) {
				ov_string_print(&query, "%s %s = %s,", query, whereFields[i], whereValues[i]);
			} else {
				ov_string_print(&query, "%s %s = %s", query, whereFields[i], whereValues[i]);
			}
		}
	}
	ov_string_print(&query, "%s%s", query, ";");

	//ov_logfile_info("%s", query);

	OV_RESULT res = Databases_MySQL_execQuery(query);
	return res;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_getComponentID(const OV_STRING table, const DB_QUERY* db_query, OV_UINT querySize, OV_STRING_VEC* result) {
	OV_STRING query = NULL;
    ov_string_setvalue(&query, "SELECT DISTINCT ComponentID0 FROM");

    for(OV_UINT i = 0; i < querySize; i++) {
    	ov_string_print(&query, "%s (SELECT DISTINCT ComponentID AS ComponentID%i FROM %s WHERE ", query, i, table);
    	for(OV_UINT j = 0; j < db_query[i].column.veclen; j++) {
    		if (j < db_query[i].column.veclen - 1)
    			ov_string_print(&query, "%s %s='%s' AND ", query, db_query[i].column.value[j], db_query[i].value.value[j]);
    		else
    			ov_string_print(&query, "%s %s='%s')", query, db_query[i].column.value[j], db_query[i].value.value[j]);
    	}
    	if (i < querySize - 1)
    		ov_string_append(&query, ",");
    }
    if (querySize > 1){
    	ov_string_append(&query, "WHERE ");
    	for(OV_UINT i = 0; i < querySize; i++) {
    		ov_string_print(&query, "%s ComponentID%i", query, i);
    		if(i < querySize-1)
    			ov_string_append(&query, "=");
    	}
    }
	ov_string_append(&query, ";");

	//ov_logfile_info("%s", query);

	OV_RESULT res = Databases_MySQL_execQuery(query);
	return res;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_execQuery(OV_STRING query) {
	if(mysql_query(MYSQL_pinst->v_db, query)) {
		ov_logfile_info("SQL Error: %s", mysql_error(MYSQL_pinst->v_db));
		ov_string_setvalue(&query, NULL);
		return OV_ERR_BADPARAM;
	}

	ov_string_setvalue(&query, NULL);
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_query_set(
    OV_INSTPTR_Databases_MySQL          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_query,value);
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_io_set(
    OV_INSTPTR_Databases_MySQL          pobj,
    const OV_BOOL  value
) {
    pobj->v_io = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT Databases_MySQL_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_Databases_MySQL pinst = Ov_StaticPtrCast(Databases_MySQL, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = openAASDiscoveryServer_DBWrapper_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    MYSQL_pinst = pinst;

    return OV_ERR_OK;
}
