
/******************************************************************************
*
*   FILE
*   ----
*   AASHttpClient.c
*
*   History
*   -------
*   2018-09-20   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_AASCrawler
#define OV_COMPILE_LIBRARY_AASCrawler
#endif


#include "AASCrawler.h"
#include "libov/ov_macros.h"


