
/******************************************************************************
*
*   FILE
*   ----
*   openaasHTTPExt.c
*
*   History
*   -------
*   2018-09-14   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_openaasHTTP
#define OV_COMPILE_LIBRARY_openaasHTTP
#endif


#include "openaasHTTP.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT openaasHTTP_openaasHTTPExt_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_openaasHTTP_openaasHTTPExt pinst = Ov_StaticPtrCast(openaasHTTP_openaasHTTPExt, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ksbase_ComTask_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_BOOL openaasHTTP_openaasHTTPExt_CheckCommand(
	const OV_INSTPTR_kshttp_httpClientHandlerExtension	pobj,
	const OV_INSTPTR_kshttp_httpclienthandler	pClientHandler,
	const OV_INSTPTR_ksbase_Channel pChannel,
	const HTTP_REQUEST request
) {
    /*    
    *   local variables
    */

    return (OV_BOOL)0;
}

OV_DLLFNCEXPORT OV_RESULT openaasHTTP_openaasHTTPExt_HandleExtendedRequest(
	const OV_INSTPTR_kshttp_httpClientHandlerExtension	pobj,
	const OV_INSTPTR_kshttp_httpclienthandler	pClientHandler,
	const OV_INSTPTR_ksbase_Channel pChannel,
	const HTTP_REQUEST request,
	HTTP_RESPONSE *response
) {
    /*    
    *   local variables
    */

    return OV_ERR_OK;
}

